# Generated by Django 5.0.6 on 2024-11-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nom_produit', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('autre_infos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intitule', models.CharField(max_length=250, unique=True)),
                ('autres_infos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Secteur d'activite",
                'verbose_name_plural': "Secteurs d'activites",
            },
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('libelle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nom_conseiller', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appServicesEvals.profession')),
                ('secteur_activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appServicesEvals.secteuractivite')),
            ],
            options={
                'verbose_name': 'Conseiller',
                'verbose_name_plural': 'Conseillers',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=250)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone_client', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_avez_vous_connu_lArcher_capital', models.CharField(choices=[('Panneau Publicitaire', 'Panneau Publicitaire'), ('Radio', 'Radio'), ('Télévision', 'Télévision'), ('Réseaux Sociaux', 'Réseaux Sociaux'), ('Magazine', 'Magazine'), ('Recommandation Tiers', 'Recommandation Tiers'), ('Autres', 'Autres')], default='Panneau Publicitaire', max_length=250)),
                ('recommanderiez_vous_lArcher_capital', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='OUI', max_length=10)),
                ('commentaire', models.TextField()),
                ('nous_suivez_vous_sur_les_reseaux', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='OUI', max_length=10)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='appServicesEvals.conseiller')),
                ('produit_souscrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='appServicesEvals.produit')),
                ('profession_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appServicesEvals.profession')),
                ('secteur_activite_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appServicesEvals.secteuractivite')),
                ('evaluation_sondages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appServicesEvals.sondage')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
    ]
